#swiftmailer:
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }

swiftmailer:
    #transport: %mailer_transport%
    host:      auth.smtp.1and1.fr
    #    host:      smtp.1and1.fr
    port:      25
    username:  projet5@gostiaux.net
    password:  Chobits69